(lang dune 3.0)

(name tradenet_sdn)

(generate_opam_files true)

(source
 (github mo-shirmohammadi/tradenet-fabric))

(authors "Mo Shirmohammadi")

(license MIT)

(package
 (name tradenet_sdn)
 (allow_empty)
 (synopsis "OCaml SDN Controller for TradeNet Fabric")
 (description
  "A software-defined networking controller that ingests real-time telemetry, computes optimal paths using Dijkstra's algorithm weighted by live network state, and dynamically pushes BGP policy changes to steer traffic across a simulated trading firm network.")
 (depends
  (ocaml
   (>= 5.0))
  dune
  lwt
  lwt_ppx
  cohttp
  cohttp-lwt-unix
  yojson
  ocamlgraph
  dream
  qcheck
  ppx_deriving))
